const fs = require('fs');
const fsPromises = require('fs/promises');
const path = require('path');
const chokidar = require('chokidar');
const { logger } = require('./logger');
const { appPaths } = require('./app-paths');
const { pluginManager } = require('../plugins/plugin-manager');

/**
 * SENTINEL — Evolution Manager
 * Handles autonomous self-improvement by dynamically writing, 
 * validating, and hot-reloading new plugins at runtime.
 */
class EvolutionManager {
  constructor() {
    this.watcher = null;
    this.isReloading = false;
  }

  initialize() {
    logger.info('evolution', 'Initializing Evolution Manager...');
    
    // Watch the user plugins directory for new/modified files
    const watchDir = appPaths.plugins;
    
    if (!fs.existsSync(watchDir)) {
      fs.mkdirSync(watchDir, { recursive: true });
    }

    this.watcher = chokidar.watch(watchDir, {
      ignored: /(^|[\/\\])\../, // ignore dotfiles
      persistent: true,
      ignoreInitial: true // don't trigger on initial scan
    });

    // Debounce reloads to prevent spamming
    let reloadTimeout = null;
    const triggerReload = (filePath) => {
      if (reloadTimeout) clearTimeout(reloadTimeout);
      reloadTimeout = setTimeout(async () => {
        await this.hotReload();
      }, 500); // Wait 500ms after last file change before reloading
    };

    this.watcher
      .on('add', (filePath) => {
        logger.info('evolution', `New plugin detected: ${path.basename(filePath)}`);
        triggerReload(filePath);
      })
      .on('change', (filePath) => {
        logger.info('evolution', `Plugin modified: ${path.basename(filePath)}`);
        triggerReload(filePath);
      })
      .on('unlink', (filePath) => {
        logger.info('evolution', `Plugin removed: ${path.basename(filePath)}`);
        triggerReload(filePath);
      });

    logger.info('evolution', 'Watching for plugin evolution events.');
  }

  /**
   * Clears require cache for plugins and tells PluginManager to reload.
   */
  async hotReload() {
    if (this.isReloading) return;
    this.isReloading = true;
    
    logger.info('evolution', 'Hot-reloading plugins...');

    try {
      // 1. Clear require cache for anything in the plugins directory
      const pluginsDir = appPaths.plugins;
      const corePluginsDir = path.join(__dirname, '../plugins/core');
      
      Object.keys(require.cache).forEach(cacheKey => {
        if (cacheKey.startsWith(pluginsDir) || cacheKey.startsWith(corePluginsDir)) {
          delete require.cache[cacheKey];
        }
      });

      // 2. Clear old plugins in memory
      pluginManager.plugins.clear();

      // 3. Re-initialize plugin manager
      await pluginManager.initialize();
      
      logger.info('evolution', 'Hot-reload complete. Neural pathways updated.');
    } catch (err) {
      logger.error('evolution', 'Failed during hot-reload', { error: err.message });
    } finally {
      this.isReloading = false;
    }
  }

  /**
   * Safely writes a new plugin generated by the AI to disk.
   */
  async evolveCapability(pluginName, description, javascriptCode) {
    logger.info('evolution', `Initiating self-evolution: ${pluginName}`);
    
    try {
      // Validate code (basic sanity check)
      if (!javascriptCode.includes('class') || !javascriptCode.includes('BasePlugin')) {
        throw new Error('Invalid plugin code. Must extend BasePlugin.');
      }

      const safeName = pluginName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
      const filePath = path.join(appPaths.plugins, `${safeName}.js`);
      
      // Write the file (Chokidar watcher will pick it up and trigger hotReload automatically)
      await fsPromises.writeFile(filePath, javascriptCode, 'utf8');
      
      return { 
        success: true, 
        message: `Successfully evolved capability '${pluginName}'. The new neural pathway is now compiling and will be available momentarily.` 
      };
    } catch (err) {
      logger.error('evolution', 'Evolution failed', { error: err.message });
      return { success: false, error: `Evolution failed: ${err.message}` };
    }
  }
}

const evolutionManager = new EvolutionManager();
module.exports = { evolutionManager };
